var nome = ("Guilherme Motta");
document.write(nome, "<br>");
var ano = 2021;
document.write("Ano - ", ano, "<br>");
var twitter = ("@guilhermemotta");
document.write("Twitter: ", twitter, "<br>");
var facebook = ("@guilhermemotta");
document.write("Facebook: ", facebook, "<br>");
var instagram = ("@guilhermemotta");
document.write("Instagram: ", instagram, "<br>");
var linkedin = ("@guilhermemotta");
document.write("LinkedIn: ", linkedin, "<br>");
var sexo = ("Masculino");
document.write("Sexo: ", sexo, "<br>");
var local = ("Porto Alegre");
document.write("Localização - Polo: ", local);
